version: '3.3'
services:
  uiapi:
    image: ${REG?Variable not set}/${APP?Variable not set}:${APP_TAG}
    container_name: ${APP_NAME}
    networks:
      - proxy
    environment:
      - DATABASE_URL=${DB_CONNSTRING}
      - DISABLE_DATABASE_SSL=true
      - ROKETO_CONTRACT_NAME=${ROKETO_CONTRACT_NAME}
      - VAULT_CONTRACT_NAME=${VAULT_CONTRACT_NAME}
      - NEAR_NETWORK_ID=${NEAR_NETWORK_ID}
      - NEAR_NODE_URL=${NEAR_NODE_URL}
      - NEAR_WALLET_URL=${NEAR_WALLET_URL}
      - API_HOST=${API_HOST}
      - DAPP_HOST=${DAPP_HOST}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=3000"
      - "traefik.http.routers.${APP_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_HOSTNAME}`, `www.${APP_HOSTNAME}`)"
networks:
  proxy:
    external:
      name: "traefik-global-proxy"
